### ISSUE TITLE
"Unable to parse whitelist" warning

### ISSUE THREAD

**Issue by vladikoff** [mozilla/emr-bootstrap-spark#14]
Seeing this new warning, wanted to make sure you know:

![image](https://cloud.githubusercontent.com/assets/128755/12524745/4df8e7e2-c12d-11e5-91e5-437fcf30bad5.png)

**Comment by vitillo** [comment]
You can safely ignore that [warning](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/telemetry/histogram_tools.py#91), thanks.
