### ISSUE TITLE
Add a directory of example notebooks.

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/emr-bootstrap-spark#3]
Instead of having a single "Hello World" notebook, it would be nice to provide several different ones showing different examples / common recipes.  Things like using accumulators, writing results out to S3, and so on.

**Comment by vladikoff** [comment]
It would be great to have example of how to read from the our S3 storage (maybe commented out, so it can still work locally and then the path can be replaced once used on http://telemetry-dash.mozilla.org/cluster/schedule)

**Comment by vitillo** [comment]
Please file the issue in Bugzilla if still applicable.
