### ISSUE TITLE
Support for spark-csv

### ISSUE THREAD

**Issue by vladikoff** [mozilla/emr-bootstrap-spark#5]
Ref https://github.com/databricks/spark-csv

I'm writing some code to be able to use `SQLContext` on CSV files using Spark. Looks something like this:
```
file_src = '../tools/out/events-2015-07-06.csv'
from pyspark.sql import SQLContext
sc = SparkContext('local')
sqlContext = SQLContext(sc)
df = sqlContext.load(source='com.databricks.spark.csv', header='true', path =file_src)
print df.select('uid').count()
```

@vitillo I'm not done with my code yet, but wanted to ask you if we will be able to use `spark-csv` on http://telemetry-dash.mozilla.org/  

To get it working locally I had to add `os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages com.databricks:spark-csv_2.10:1.2.0'` to my Spark launcher

Let me know your thoughts, because if we cannot use spark-csv then I will have to change my scripts

**Comment by vitillo** [comment]
It should be possible; you could modify the [PYSPARK_SUBMIT_ARGS](https://github.com/mozilla/emr-bootstrap-spark/blob/master/telemetry.sh#L134) environment variable in the script but you are going to have to pick a stable version number for spark-csv and stick to it.

Before submitting a PR, you should test the bootstrap script by launching an EMR cluster from the command line, as shown in the [README](https://github.com/mozilla/emr-bootstrap-spark/blob/master/README.md).

**Comment by vladikoff** [comment]
@vitillo I use a cloudservices aws dev account and tried to deploy one, but got this error in the AWS Console:
``
Failed to provision ec2 instances because 'Value (telemetry-spark-emr) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name 
```

**Comment by vladikoff** [comment]
`Path=s3://telemetry-spark-emr/telemetry.sh`

Also I noticed that the bootstrap scripts live on S3, I guess should adjust those values and point to a different bucket with my changes?

**Comment by vitillo** [comment]
I have tested the deployment this time. In the meantime you should get credentials, from Wesley Dawson, for "moz-svc-dev" which the account where our Spark infrastructure is currently deployed.
